Repository massalabs/massa-sc-runtime, pull requests merged in 2021-12, with the labels that each got.

#20 Add status badges to README
  README.md
Labels: documentation

#13 Define module as a lib
  Cargo.lock
  Cargo.toml
  execution/Cargo.toml
  src/env.rs
  src/execution_impl.rs
  src/interface.rs
  src/lib.rs
  src/main.rs
  src/settings.rs
  src/tests.rs
  src/types.rs
Labels: smart contracts

#19 Be able to call a WASM module (compiled from AssemblyScript)
  .gitignore
  Cargo.lock
  Cargo.toml
  src/env.rs
  src/execution_impl.rs
  src/lib.rs
  src/tests.rs
Labels: smart contracts

#33 Call module return result.
  src/execution_impl.rs
Labels: smart contracts

#32 Rename how many.
  src/env.rs
  src/execution_impl.rs
  wasm/assembly/massa.ts
Labels: smart contracts

#34 Test calling a not exported function.
  src/execution_impl.rs
  src/tests.rs
  wasm/assembly/get_string.ts
  wasm/assembly/local_hello_name_caller.ts
  wasm/build/get_string.wasm.map
  wasm/build/local_hello_name_caller.wat
  wasm/package.json
Labels: smart contracts

#36 Add configuration tags
  src/settings.rs
Labels: enhancement

#35 Use trait for interface
  .gitignore
  src/env.rs
  src/execution_impl.rs
  src/tests.rs
  src/types.rs
  wasm/build/caller.wasm
  wasm/build/caller.wasm.map
  wasm/build/get_string.wasm
  wasm/build/get_string.wasm.map
Labels: smart contracts

#37 Add documentation for the abort fn
  src/env.rs
  src/execution_impl.rs
Labels: documentation

#47 :chart_with_upwards_trend: For a better coverage, don't test dependencies & interface
  .github/action-rs/grcov.yml
Labels: documentation

#48 Add the *create smart contract* ABI
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/abi_impl.rs
  src/env.rs
  src/execution_impl.rs
  src/settings.rs
  src/tests.rs
  wasm/.gitignore
  wasm/assembly/create_sc.ts
  wasm/assembly/massa.ts
  wasm/build/create_sc.wasm
  wasm/massa_tools/include_base64.js
  wasm/massa_tools/match.test.js
  wasm/massa_tools/match_include_base64.js
  wasm/package.json
  wasm/yarn.lock
Labels: enhancement
